### ISSUE TITLE
Node-RED doesn't see images

### ISSUE THREAD

**Issue by stas-malavin** [PlanktoScope/pallet-segmenter#1]
Hi Ethan,

I'm trying to set up ```pallet-segmenter``` on my Ubuntu laptop.
Followed the instructions, everything seems to work fine (except that there's just one ```edge``` brunch instead of ```main``` in ```README.md```).
However, I can't see any folder in the ```Node-RED``` dashboard, while the ```File Browser``` works and sees what is supposed.
![segmenter-issue](https://github.com/PlanktoScope/pallet-segmenter/assets/17991942/4b943555-0703-46f1-95d7-8e213f0b86de)

Another question, how do I run the ```pallet-segmenter``` without pulling the images each time with ```sudo -E forklift plt apply```?
Should I run all the Docker containers one by one manually?

Thank you,
Stas

**Comment by ethanjli** [comment]
Hi, Stas - thanks so much for trying out this repository and reporting these issues! To address each item:

- `edge` branch instead of `main` in `README.md`: good catch, thanks for mentioning this typo! I've fixed this error in the README now.
- `forklift plt apply` pulling images every time: Two weeks ago I updated the `forklift` tool to a new version (v0.7.0, though now the latest version is v0.7.1) which changes the behavior of `forklift plt apply` - but I had forgotten to update the usage instructions in this repository's README to change the commands in the usage instructions so that they account for the changed behavior of the `forklift` tool. I've updated the README now - can you confirm that you're running v0.7.0 or v0.7.1 of `forklift` (by running `forklift --version`), and then see if the updated README instructions solve the problems you had with the Docker container images being pulled at unnecessary/inconvenient times?
- Node-RED dashboard doesn't see any folders even though File Browser sees folders: I've pushed a commit now which simplifies how the pallet makes the data folder available to the Node-RED dashboard, to match what the pallet does for the File Browser - hopefully this will fix the problem. Can you see if the issue is resolved if you just follow the updated README instructions?

**Comment by stas-malavin** [comment]
Hi Ethan,
Sorry for the late reply — thank you for the answer!
Unfortunately, I still can't see the ```~/.local/share/planktoscope/data/img``` folder (or any other) from Node-RED dashboard. The list of folders is just empty…
I'm running ```forklift``` v0.7.1. ```sudo -E forklift stage apply``` command works like a charm.

Here's a log, not sure if the error is somehow related to the problem or not
[2024-05-15_18-42-24_252151.log](https://github.com/PlanktoScope/pallet-segmenter/files/15325784/2024-05-15_18-42-24_252151.log)

**Comment by ethanjli** [comment]
Hi, Stas - sorry about the slow response on my end. The situation leading to the problem you're experiencing seems to be a bit complicated, so it'll take some more time for me to figure out some next steps for troubleshooting this problem. I'll send another reply once I have some things for you to try out!

**Comment by ethanjli** [comment]
Hi, Stas! It's been a long time, but I finally identified one problem which might be the cause of at least some of the problems you encountered; and I think I've probably fixed it in dc0446d138429d6981af9f96c830446f165ee61a, 331215beb13b1c2b5467b80a7c7305e325988bf4, and e3b4a36d2dd6c9972ef50d989c255cd30a0d3b84 in the `edge` branch of this repo. If you delete Forklift and `~/.local/share/planktoscope` from your computer and then go through the README from the beginning, I think it _might_ work for you now.

**Comment by stas-malavin** [comment]
Hi Ethan,
Thanks for the update! Unfortunately, I currently have no access to
planktoscope and can't check it out. I'll get to it later and let you know.
Best, Stas
